version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: spring-boot-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tv_application
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-proot", "-hlocalhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  mysql_data: